namespace Kontainr.Models;

public static class AppTemplates
{
    public static readonly List<AppTemplate> Templates =
    [
        // ── Web Servers ─────────────────────────────────────────────
        new("Nginx", "Web Server", "nginx:alpine", [("80", "80")], [], "unless-stopped", "https://hub.docker.com/_/nginx",
            "High-performance web server and reverse proxy known for its stability and low resource consumption."),
        new("Apache", "Web Server", "httpd:alpine", [("80", "80")], [], "unless-stopped", "https://hub.docker.com/_/httpd",
            "The world's most widely used web server, offering powerful configuration via .htaccess files."),
        new("Caddy", "Web Server", "caddy:2-alpine", [("80", "80"), ("443", "443")], [], "unless-stopped", "https://hub.docker.com/_/caddy",
            "Modern web server with automatic HTTPS, HTTP/3 support, and a simple configuration syntax."),
        new("Lighttpd", "Web Server", "sebp/lighttpd:latest", [("80", "80")], [], "unless-stopped", "https://hub.docker.com/r/sebp/lighttpd",
            "Lightweight web server optimized for speed-critical environments with minimal memory footprint."),
        new("OpenResty", "Web Server", "openresty/openresty:alpine", [("80", "80")], [], "unless-stopped", "https://hub.docker.com/r/openresty/openresty",
            "Nginx-based web platform with built-in Lua scripting for building dynamic web apps and API gateways."),

        // ── Reverse Proxies & Load Balancers ────────────────────────
        new("Traefik", "Reverse Proxy", "traefik:v3.0", [("80", "80"), ("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/_/traefik",
            "Cloud-native reverse proxy with automatic service discovery and built-in Let's Encrypt support."),
        new("Nginx Proxy Manager", "Reverse Proxy", "jc21/nginx-proxy-manager:latest", [("80", "80"), ("81", "81"), ("443", "443")], [], "unless-stopped", "https://hub.docker.com/r/jc21/nginx-proxy-manager",
            "Easy-to-use reverse proxy GUI for managing Nginx proxy hosts, SSL certificates, and redirects."),
        new("HAProxy", "Load Balancer", "haproxy:alpine", [("80", "80"), ("8404", "8404")], [], "unless-stopped", "https://hub.docker.com/_/haproxy",
            "Reliable, high-performance TCP/HTTP load balancer used by many large-scale production environments."),
        new("Envoy", "Reverse Proxy", "envoyproxy/envoy:v1.30-latest", [("10000", "10000"), ("9901", "9901")], [], "unless-stopped", "https://hub.docker.com/r/envoyproxy/envoy",
            "Cloud-native edge and service proxy designed for microservices with advanced observability features."),

        // ── Databases ───────────────────────────────────────────────
        new("PostgreSQL", "Database", "postgres:16-alpine", [("5432", "5432")],
            [("POSTGRES_PASSWORD", "changeme"), ("POSTGRES_DB", "mydb")], "unless-stopped", "https://hub.docker.com/_/postgres",
            "Advanced open-source relational database with strong SQL compliance, JSONB support, and extensibility."),
        new("MySQL", "Database", "mysql:8", [("3306", "3306")],
            [("MYSQL_ROOT_PASSWORD", "changeme"), ("MYSQL_DATABASE", "mydb")], "unless-stopped", "https://hub.docker.com/_/mysql",
            "The world's most popular open-source relational database, widely used for web applications."),
        new("MariaDB", "Database", "mariadb:11", [("3306", "3306")],
            [("MARIADB_ROOT_PASSWORD", "changeme"), ("MARIADB_DATABASE", "mydb")], "unless-stopped", "https://hub.docker.com/_/mariadb",
            "Community-developed fork of MySQL with enhanced performance, storage engines, and features."),
        new("MongoDB", "Database", "mongo:7", [("27017", "27017")], [], "unless-stopped", "https://hub.docker.com/_/mongo",
            "Document-oriented NoSQL database that stores data in flexible, JSON-like documents."),
        new("Redis", "Database", "redis:7-alpine", [("6379", "6379")], [], "unless-stopped", "https://hub.docker.com/_/redis",
            "In-memory data store used as a database, cache, and message broker with sub-millisecond latency."),
        new("Valkey", "Database", "valkey/valkey:latest", [("6379", "6379")], [], "unless-stopped", "https://hub.docker.com/r/valkey/valkey",
            "Open-source Redis fork maintained by the Linux Foundation, offering a community-driven alternative."),
        new("InfluxDB", "Database", "influxdb:2", [("8086", "8086")], [], "unless-stopped", "https://hub.docker.com/_/influxdb",
            "Purpose-built time series database for high-write and query loads from metrics and IoT data."),
        new("CouchDB", "Database", "couchdb:3", [("5984", "5984")],
            [("COUCHDB_USER", "admin"), ("COUCHDB_PASSWORD", "changeme")], "unless-stopped", "https://hub.docker.com/_/couchdb",
            "Document-oriented NoSQL database with multi-master replication and an HTTP/JSON API."),
        new("Cassandra", "Database", "cassandra:5", [("9042", "9042")], [], "unless-stopped", "https://hub.docker.com/_/cassandra",
            "Distributed wide-column NoSQL database designed for high availability across multiple data centers."),
        new("Neo4j", "Database", "neo4j:5", [("7474", "7474"), ("7687", "7687")],
            [("NEO4J_AUTH", "neo4j/changeme")], "unless-stopped", "https://hub.docker.com/_/neo4j",
            "Graph database for storing and querying highly connected data using the Cypher query language."),
        new("ClickHouse", "Database", "clickhouse/clickhouse-server:latest", [("8123", "8123"), ("9000", "9000")], [], "unless-stopped", "https://hub.docker.com/r/clickhouse/clickhouse-server",
            "Column-oriented OLAP database designed for real-time analytics on large datasets."),
        new("SurrealDB", "Database", "surrealdb/surrealdb:latest", [("8000", "8000")], [], "unless-stopped", "https://hub.docker.com/r/surrealdb/surrealdb",
            "Multi-model database supporting document, graph, and relational paradigms with real-time queries."),
        new("Elasticsearch", "Database", "docker.elastic.co/elasticsearch/elasticsearch:8.13.0", [("9200", "9200"), ("9300", "9300")],
            [("discovery.type", "single-node"), ("xpack.security.enabled", "false")], "unless-stopped", "https://hub.docker.com/_/elasticsearch",
            "Distributed search and analytics engine for full-text search, logging, and real-time data analysis."),
        new("Meilisearch", "Database", "getmeili/meilisearch:latest", [("7700", "7700")], [], "unless-stopped", "https://hub.docker.com/r/getmeili/meilisearch",
            "Lightning-fast, typo-tolerant search engine designed for instant and relevant search experiences."),
        new("Typesense", "Database", "typesense/typesense:latest", [("8108", "8108")],
            [("TYPESENSE_API_KEY", "changeme"), ("TYPESENSE_DATA_DIR", "/data")], "unless-stopped", "https://hub.docker.com/r/typesense/typesense",
            "Open-source search engine optimized for instant search-as-you-type experiences with typo tolerance."),
        new("Minio", "Object Storage", "minio/minio:latest", [("9000", "9000"), ("9001", "9001")],
            [("MINIO_ROOT_USER", "minioadmin"), ("MINIO_ROOT_PASSWORD", "changeme")], "unless-stopped", "https://hub.docker.com/r/minio/minio",
            "S3-compatible object storage server for building private cloud storage infrastructure."),
        new("Memcached", "Cache", "memcached:alpine", [("11211", "11211")], [], "unless-stopped", "https://hub.docker.com/_/memcached",
            "High-performance distributed memory caching system for speeding up dynamic web applications."),
        new("KeyDB", "Database", "eqalpha/keydb:latest", [("6379", "6379")], [], "unless-stopped", "https://hub.docker.com/r/eqalpha/keydb",
            "Multithreaded Redis fork with higher throughput and active replication support."),
        new("RethinkDB", "Database", "rethinkdb:latest", [("8080", "8080"), ("28015", "28015")], [], "unless-stopped", "https://hub.docker.com/_/rethinkdb",
            "Document database with built-in real-time change feeds for pushing live updates to applications."),
        new("ArangoDB", "Database", "arangodb:latest", [("8529", "8529")],
            [("ARANGO_ROOT_PASSWORD", "changeme")], "unless-stopped", "https://hub.docker.com/_/arangodb",
            "Native multi-model database supporting documents, graphs, and key-value pairs in a single engine."),

        // ── DB Admin Tools ──────────────────────────────────────────
        new("Adminer", "DB Admin", "adminer:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/_/adminer",
            "Lightweight database management tool supporting MySQL, PostgreSQL, SQLite, and more in a single PHP file."),
        new("pgAdmin", "DB Admin", "dpage/pgadmin4:latest", [("5050", "80")],
            [("PGADMIN_DEFAULT_EMAIL", "admin@local.dev"), ("PGADMIN_DEFAULT_PASSWORD", "changeme")], "unless-stopped", "https://hub.docker.com/r/dpage/pgadmin4",
            "Feature-rich web-based administration tool for PostgreSQL with query tools and server monitoring."),
        new("phpMyAdmin", "DB Admin", "phpmyadmin:latest", [("8081", "80")],
            [("PMA_ARBITRARY", "1")], "unless-stopped", "https://hub.docker.com/_/phpmyadmin",
            "Web-based MySQL and MariaDB administration interface for managing databases, tables, and queries."),
        new("Mongo Express", "DB Admin", "mongo-express:latest", [("8081", "8081")],
            [("ME_CONFIG_BASICAUTH_USERNAME", "admin"), ("ME_CONFIG_BASICAUTH_PASSWORD", "changeme")], "unless-stopped", "https://hub.docker.com/_/mongo-express",
            "Web-based MongoDB admin interface for browsing collections, documents, and running queries."),
        new("RedisInsight", "DB Admin", "redis/redisinsight:latest", [("5540", "5540")], [], "unless-stopped", "https://hub.docker.com/r/redis/redisinsight",
            "Official Redis GUI for browsing keys, running commands, and profiling Redis performance."),
        new("Kibana", "DB Admin", "docker.elastic.co/kibana/kibana:8.13.0", [("5601", "5601")], [], "unless-stopped", "https://hub.docker.com/_/kibana",
            "Visualization and exploration tool for Elasticsearch data with dashboards and real-time analytics."),
        new("CloudBeaver", "DB Admin", "dbeaver/cloudbeaver:latest", [("8978", "8978")], [], "unless-stopped", "https://hub.docker.com/r/dbeaver/cloudbeaver",
            "Web-based database manager supporting multiple database engines with a rich SQL editor."),

        // ── Message Queues ──────────────────────────────────────────
        new("RabbitMQ", "Message Queue", "rabbitmq:3-management-alpine", [("5672", "5672"), ("15672", "15672")], [], "unless-stopped", "https://hub.docker.com/_/rabbitmq",
            "Widely deployed message broker supporting AMQP, MQTT, and STOMP with a built-in management UI."),
        new("NATS", "Message Queue", "nats:latest", [("4222", "4222"), ("8222", "8222")], [], "unless-stopped", "https://hub.docker.com/_/nats",
            "High-performance cloud-native messaging system with at-most-once and exactly-once delivery."),
        new("Mosquitto", "Message Queue", "eclipse-mosquitto:2", [("1883", "1883"), ("9001", "9001")], [], "unless-stopped", "https://hub.docker.com/_/eclipse-mosquitto",
            "Lightweight MQTT message broker ideal for IoT devices and low-bandwidth communication."),
        new("Kafka (Redpanda)", "Message Queue", "redpandadata/redpanda:latest", [("9092", "9092"), ("8082", "8082")], [], "unless-stopped", "https://hub.docker.com/r/redpandadata/redpanda",
            "Kafka-compatible streaming platform with no ZooKeeper dependency and lower latency."),
        new("EMQX", "Message Queue", "emqx/emqx:latest", [("1883", "1883"), ("18083", "18083")], [], "unless-stopped", "https://hub.docker.com/r/emqx/emqx",
            "Scalable MQTT broker for IoT, IIoT, and connected vehicles with built-in rule engine."),

        // ── Monitoring & Observability ───────────────────────────────
        new("Grafana", "Monitoring", "grafana/grafana:latest", [("3000", "3000")], [], "unless-stopped", "https://hub.docker.com/r/grafana/grafana",
            "Open-source analytics and visualization platform for creating dashboards from multiple data sources."),
        new("Prometheus", "Monitoring", "prom/prometheus:latest", [("9090", "9090")], [], "unless-stopped", "https://hub.docker.com/r/prom/prometheus",
            "Time series monitoring system with a powerful query language and alerting capabilities."),
        new("Uptime Kuma", "Monitoring", "louislam/uptime-kuma:latest", [("3001", "3001")], [], "unless-stopped", "https://hub.docker.com/r/louislam/uptime-kuma",
            "Self-hosted uptime monitoring tool with a beautiful UI and notifications via 90+ services."),
        new("Netdata", "Monitoring", "netdata/netdata:latest", [("19999", "19999")], [], "unless-stopped", "https://hub.docker.com/r/netdata/netdata",
            "Real-time performance monitoring with per-second metrics and automatic anomaly detection."),
        new("cAdvisor", "Monitoring", "gcr.io/cadvisor/cadvisor:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/r/google/cadvisor",
            "Container resource usage and performance analyzer providing real-time metrics for running containers."),
        new("Loki", "Monitoring", "grafana/loki:latest", [("3100", "3100")], [], "unless-stopped", "https://hub.docker.com/r/grafana/loki",
            "Log aggregation system by Grafana Labs designed to store and query logs efficiently."),
        new("Jaeger", "Monitoring", "jaegertracing/all-in-one:latest", [("16686", "16686"), ("4318", "4318")], [], "unless-stopped", "https://hub.docker.com/r/jaegertracing/all-in-one",
            "Distributed tracing platform for monitoring and troubleshooting microservices-based architectures."),
        new("Zipkin", "Monitoring", "openzipkin/zipkin:latest", [("9411", "9411")], [], "unless-stopped", "https://hub.docker.com/r/openzipkin/zipkin",
            "Distributed tracing system for gathering timing data to troubleshoot latency issues in services."),
        new("Graylog", "Monitoring", "graylog/graylog:6.0", [("9000", "9000"), ("12201", "12201")],
            [("GRAYLOG_PASSWORD_SECRET", "changeme16chars!"), ("GRAYLOG_ROOT_PASSWORD_SHA2", "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918")], "unless-stopped", "https://hub.docker.com/r/graylog/graylog",
            "Centralized log management platform with powerful search, dashboards, and alerting."),
        new("Zabbix", "Monitoring", "zabbix/zabbix-appliance:latest", [("8080", "80"), ("10051", "10051")], [], "unless-stopped", "https://hub.docker.com/r/zabbix/zabbix-appliance",
            "Enterprise-grade monitoring solution for networks, servers, and cloud services with auto-discovery."),
        new("Healthchecks", "Monitoring", "lscr.io/linuxserver/healthchecks:latest", [("8000", "8000")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/healthchecks",
            "Cron job monitoring service that listens for pings and alerts when scheduled tasks fail."),
        new("Gotify", "Monitoring", "gotify/server:latest", [("8080", "80")], [], "unless-stopped", "https://hub.docker.com/r/gotify/server",
            "Self-hosted push notification server with a simple API and Android app support."),
        new("Ntfy", "Monitoring", "binwiederhier/ntfy:latest", [("8080", "80")], [], "unless-stopped", "https://hub.docker.com/r/binwiederhier/ntfy",
            "Simple HTTP-based pub-sub notification service for sending push notifications to phones and desktops."),
        new("Changedetection.io", "Monitoring", "ghcr.io/dgtlmoon/changedetection.io:latest", [("5000", "5000")], [], "unless-stopped", "https://hub.docker.com/r/dgtlmoon/changedetection.io",
            "Website change detection and monitoring tool with notifications when web pages are updated."),
        new("Dozzle", "Monitoring", "amir20/dozzle:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/r/amir20/dozzle",
            "Real-time log viewer for Docker containers with a lightweight web interface."),

        // ── Home Automation ─────────────────────────────────────────
        new("Home Assistant", "Home Automation", "homeassistant/home-assistant:stable", [("8123", "8123")], [], "unless-stopped", "https://hub.docker.com/r/homeassistant/home-assistant",
            "Open-source home automation platform supporting thousands of smart home devices and integrations."),
        new("Node-RED", "Home Automation", "nodered/node-red:latest", [("1880", "1880")], [], "unless-stopped", "https://hub.docker.com/r/nodered/node-red",
            "Flow-based programming tool for wiring together IoT devices, APIs, and online services."),
        new("Mosquitto", "Home Automation", "eclipse-mosquitto:2", [("1883", "1883")], [], "unless-stopped", "https://hub.docker.com/_/eclipse-mosquitto",
            "Lightweight MQTT broker commonly used as the messaging backbone for home automation systems."),
        new("Zigbee2MQTT", "Home Automation", "koenkk/zigbee2mqtt:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/r/koenkk/zigbee2mqtt",
            "Bridge that connects Zigbee smart devices to MQTT without a proprietary Zigbee hub."),
        new("ESPHome", "Home Automation", "ghcr.io/esphome/esphome:latest", [("6052", "6052")], [], "unless-stopped", "https://hub.docker.com/r/esphome/esphome",
            "System for controlling ESP8266/ESP32 microcontrollers with simple YAML configuration files."),
        new("Scrypted", "Home Automation", "koush/scrypted:latest", [("10443", "10443")], [], "unless-stopped", "https://hub.docker.com/r/koush/scrypted",
            "Home video integration platform for bringing cameras into HomeKit, Google Home, and Alexa."),

        // ── Dashboards ──────────────────────────────────────────────
        new("Heimdall", "Dashboard", "lscr.io/linuxserver/heimdall:latest", [("80", "80"), ("443", "443")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/heimdall",
            "Application dashboard for organizing and launching your self-hosted web apps from one page."),
        new("Homepage", "Dashboard", "ghcr.io/gethomepage/homepage:latest", [("3000", "3000")], [], "unless-stopped", "https://hub.docker.com/r/gethomepage/homepage",
            "Highly customizable application dashboard with service integrations and real-time status widgets."),
        new("Homarr", "Dashboard", "ghcr.io/ajnart/homarr:latest", [("7575", "7575")], [], "unless-stopped", "https://hub.docker.com/r/ajnart/homarr",
            "Sleek server dashboard with drag-and-drop tiles, calendar integration, and service health monitoring."),
        new("Dashy", "Dashboard", "lissy93/dashy:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/r/lissy93/dashy",
            "Feature-rich self-hosted dashboard with themes, status checks, widgets, and a built-in editor."),
        new("Organizr", "Dashboard", "organizr/organizr:latest", [("80", "80")], [], "unless-stopped", "https://hub.docker.com/r/organizr/organizr",
            "HTPC/homelab organizer that embeds your services into a single tabbed browser interface."),
        new("Flame", "Dashboard", "pawelmalak/flame:latest", [("5005", "5005")], [], "unless-stopped", "https://hub.docker.com/r/pawelmalak/flame",
            "Minimalist self-hosted startpage with bookmarks, application links, and a built-in editor."),

        // ── Media Servers ───────────────────────────────────────────
        new("Jellyfin", "Media", "jellyfin/jellyfin:latest", [("8096", "8096")], [], "unless-stopped", "https://hub.docker.com/r/jellyfin/jellyfin",
            "Free and open-source media server for streaming movies, TV shows, music, and photos."),
        new("Plex", "Media", "lscr.io/linuxserver/plex:latest", [("32400", "32400")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/plex",
            "Popular media server that organizes and streams your personal media to any device."),
        new("Emby", "Media", "emby/embyserver:latest", [("8096", "8096")], [], "unless-stopped", "https://hub.docker.com/r/emby/embyserver",
            "Personal media server for organizing, playing, and streaming video, music, and photos."),
        new("Navidrome", "Media", "deluan/navidrome:latest", [("4533", "4533")], [], "unless-stopped", "https://hub.docker.com/r/deluan/navidrome",
            "Lightweight self-hosted music server compatible with Subsonic and Airsonic clients."),
        new("Airsonic-Advanced", "Media", "lscr.io/linuxserver/airsonic-advanced:latest", [("4040", "4040")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/airsonic-advanced",
            "Community-driven music streaming server forked from Airsonic with modern features."),
        new("Calibre-Web", "Media", "lscr.io/linuxserver/calibre-web:latest", [("8083", "8083")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/calibre-web",
            "Web-based e-book manager for browsing, reading, and downloading books from a Calibre library."),
        new("Kavita", "Media", "jvmilazz0/kavita:latest", [("5000", "5000")], [], "unless-stopped", "https://hub.docker.com/r/jvmilazz0/kavita",
            "Self-hosted digital library for manga, comics, and books with a modern reading experience."),
        new("Audiobookshelf", "Media", "ghcr.io/advplyr/audiobookshelf:latest", [("13378", "80")], [], "unless-stopped", "https://hub.docker.com/r/advplyr/audiobookshelf",
            "Self-hosted audiobook and podcast server with progress tracking and mobile apps."),
        new("PhotoPrism", "Media", "photoprism/photoprism:latest", [("2342", "2342")],
            [("PHOTOPRISM_ADMIN_PASSWORD", "changeme")], "unless-stopped", "https://hub.docker.com/r/photoprism/photoprism",
            "AI-powered photo management app with automatic tagging, face recognition, and geo-mapping."),
        new("Immich", "Media", "ghcr.io/immich-app/immich-server:latest", [("2283", "2283")], [], "unless-stopped", "https://hub.docker.com/r/altran1502/immich-server",
            "Self-hosted Google Photos alternative with mobile auto-backup, AI search, and shared albums."),
        new("Stash", "Media", "stashapp/stash:latest", [("9999", "9999")], [], "unless-stopped", "https://hub.docker.com/r/stashapp/stash",
            "Media organizer for managing and tagging your personal media collection with metadata scraping."),

        // ── *arr Stack ──────────────────────────────────────────────
        new("Sonarr", "*arr Stack", "lscr.io/linuxserver/sonarr:latest", [("8989", "8989")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/sonarr",
            "TV series management and automation tool that monitors, downloads, and organizes episodes."),
        new("Radarr", "*arr Stack", "lscr.io/linuxserver/radarr:latest", [("7878", "7878")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/radarr",
            "Movie collection manager that automates downloading and organizing films from Usenet and torrents."),
        new("Lidarr", "*arr Stack", "lscr.io/linuxserver/lidarr:latest", [("8686", "8686")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/lidarr",
            "Music collection manager that monitors artists and automatically downloads new albums."),
        new("Readarr", "*arr Stack", "lscr.io/linuxserver/readarr:develop", [("8787", "8787")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/readarr",
            "E-book and audiobook collection manager for tracking authors and downloading new releases."),
        new("Whisparr", "*arr Stack", "ghcr.io/hotio/whisparr:latest", [("6969", "6969")], [], "unless-stopped", "https://hub.docker.com/r/hotio/whisparr",
            "Adult content collection manager in the *arr family with automated downloading and organizing."),
        new("Prowlarr", "*arr Stack", "lscr.io/linuxserver/prowlarr:latest", [("9696", "9696")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/prowlarr",
            "Indexer manager that integrates with Sonarr, Radarr, and other *arr apps for unified search."),
        new("Bazarr", "*arr Stack", "lscr.io/linuxserver/bazarr:latest", [("6767", "6767")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/bazarr",
            "Companion app for Sonarr and Radarr that automatically downloads subtitles for your media."),
        new("Overseerr", "*arr Stack", "lscr.io/linuxserver/overseerr:latest", [("5055", "5055")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/overseerr",
            "Media request and discovery tool that integrates with Plex, Sonarr, and Radarr."),
        new("Requestrr", "*arr Stack", "thomst08/requestrr:latest", [("4545", "4545")], [], "unless-stopped", "https://hub.docker.com/r/thomst08/requestrr",
            "Discord chatbot for requesting movies and TV shows through Sonarr, Radarr, and Overseerr."),
        new("Tautulli", "*arr Stack", "lscr.io/linuxserver/tautulli:latest", [("8181", "8181")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/tautulli",
            "Plex media server monitoring tool with detailed analytics, history, and notifications."),
        new("Flaresolverr", "*arr Stack", "ghcr.io/flaresolverr/flaresolverr:latest", [("8191", "8191")], [], "unless-stopped", "https://hub.docker.com/r/flaresolverr/flaresolverr",
            "Proxy server for bypassing Cloudflare protection, used by Prowlarr and Jackett indexers."),
        new("Recyclarr", "*arr Stack", "ghcr.io/recyclarr/recyclarr:latest", [], [], "unless-stopped", "https://hub.docker.com/r/recyclarr/recyclarr",
            "Automatically syncs TRaSH Guides quality profiles and custom formats to Sonarr and Radarr."),
        new("Autobrr", "*arr Stack", "ghcr.io/autobrr/autobrr:latest", [("7474", "7474")], [], "unless-stopped", "https://hub.docker.com/r/autobrr/autobrr",
            "Modern download automation tool for monitoring IRC announce channels and RSS feeds."),
        new("Unpackerr", "*arr Stack", "ghcr.io/unpackerr/unpackerr:latest", [], [], "unless-stopped", "https://hub.docker.com/r/unpackerr/unpackerr",
            "Extracts downloaded archives so Sonarr, Radarr, and Lidarr can import completed downloads."),
        new("Jackett", "*arr Stack", "lscr.io/linuxserver/jackett:latest", [("9117", "9117")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/jackett",
            "Torrent indexer proxy that translates queries from *arr apps to tracker-specific searches."),

        // ── Download Clients ────────────────────────────────────────
        new("qBittorrent", "Download Client", "lscr.io/linuxserver/qbittorrent:latest", [("8080", "8080"), ("6881", "6881")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/qbittorrent",
            "Feature-rich open-source BitTorrent client with a web UI and extensive plugin support."),
        new("Transmission", "Download Client", "lscr.io/linuxserver/transmission:latest", [("9091", "9091"), ("51413", "51413")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/transmission",
            "Lightweight BitTorrent client known for its minimal resource usage and clean web interface."),
        new("Deluge", "Download Client", "lscr.io/linuxserver/deluge:latest", [("8112", "8112"), ("6881", "6881")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/deluge",
            "Lightweight, cross-platform BitTorrent client with a plugin-based architecture."),
        new("SABnzbd", "Download Client", "lscr.io/linuxserver/sabnzbd:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/sabnzbd",
            "Usenet binary newsreader with an intuitive web interface for automated NZB downloading."),
        new("NZBGet", "Download Client", "lscr.io/linuxserver/nzbget:latest", [("6789", "6789")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/nzbget",
            "Efficient Usenet downloader written in C++ for maximum performance on low-end hardware."),
        new("JDownloader 2", "Download Client", "jlesage/jdownloader-2:latest", [("5800", "5800")], [], "unless-stopped", "https://hub.docker.com/r/jlesage/jdownloader-2",
            "Open-source download manager supporting file hosts, one-click hosters, and CAPTCHA solving."),
        new("Aria2", "Download Client", "p3terx/aria2-pro:latest", [("6800", "6800"), ("6888", "6888")], [], "unless-stopped", "https://hub.docker.com/r/p3terx/aria2-pro",
            "Ultra-fast download utility supporting HTTP, FTP, BitTorrent, and Metalink protocols."),

        // ── Dev Tools ───────────────────────────────────────────────
        new("Gitea", "Dev Tools", "gitea/gitea:latest", [("3000", "3000"), ("2222", "22")], [], "unless-stopped", "https://hub.docker.com/r/gitea/gitea",
            "Lightweight self-hosted Git service with issue tracking, pull requests, and CI/CD."),
        new("GitLab", "Dev Tools", "gitlab/gitlab-ce:latest", [("8929", "80"), ("2224", "22")], [], "unless-stopped", "https://hub.docker.com/r/gitlab/gitlab-ce",
            "Complete DevOps platform with Git hosting, CI/CD pipelines, issue tracking, and container registry."),
        new("Forgejo", "Dev Tools", "codeberg.org/forgejo/forgejo:latest", [("3000", "3000"), ("2222", "22")], [], "unless-stopped", "https://hub.docker.com/r/codeberg/forgejo",
            "Community-owned Gitea fork focused on sustainability and independence as a self-hosted Git forge."),
        new("Code Server", "Dev Tools", "lscr.io/linuxserver/code-server:latest", [("8443", "8443")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/code-server",
            "VS Code running in the browser, accessible from any device with a full development environment."),
        new("Drone", "Dev Tools", "drone/drone:latest", [("8000", "80")], [], "unless-stopped", "https://hub.docker.com/r/drone/drone",
            "Container-native CI/CD platform that automates build, test, and release workflows."),
        new("Jenkins", "Dev Tools", "jenkins/jenkins:lts", [("8080", "8080"), ("50000", "50000")], [], "unless-stopped", "https://hub.docker.com/r/jenkins/jenkins",
            "Leading open-source automation server with hundreds of plugins for building and deploying software."),
        new("SonarQube", "Dev Tools", "sonarqube:community", [("9000", "9000")], [], "unless-stopped", "https://hub.docker.com/_/sonarqube",
            "Code quality and security analysis platform that detects bugs, vulnerabilities, and code smells."),
        new("Registry", "Dev Tools", "registry:2", [("5000", "5000")], [], "unless-stopped", "https://hub.docker.com/_/registry",
            "Official Docker image registry for hosting and distributing container images privately."),
        new("Nexus", "Dev Tools", "sonatype/nexus3:latest", [("8081", "8081")], [], "unless-stopped", "https://hub.docker.com/r/sonatype/nexus3",
            "Universal repository manager for Maven, npm, Docker, and other package formats."),
        new("Verdaccio", "Dev Tools", "verdaccio/verdaccio:latest", [("4873", "4873")], [], "unless-stopped", "https://hub.docker.com/r/verdaccio/verdaccio",
            "Lightweight private npm proxy registry for caching and publishing internal packages."),
        new("n8n", "Dev Tools", "n8nio/n8n:latest", [("5678", "5678")], [], "unless-stopped", "https://hub.docker.com/r/n8nio/n8n",
            "Workflow automation tool with 200+ integrations for connecting apps and automating tasks visually."),
        new("Budibase", "Dev Tools", "budibase/budibase:latest", [("10000", "80")], [], "unless-stopped", "https://hub.docker.com/r/budibase/budibase",
            "Low-code platform for building internal tools, forms, and admin panels in minutes."),
        new("Nocodb", "Dev Tools", "nocodb/nocodb:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/r/nocodb/nocodb",
            "Open-source Airtable alternative that turns any database into a smart spreadsheet interface."),
        new("Directus", "Dev Tools", "directus/directus:latest", [("8055", "8055")],
            [("SECRET", "changeme"), ("ADMIN_EMAIL", "admin@local.dev"), ("ADMIN_PASSWORD", "changeme")], "unless-stopped", "https://hub.docker.com/r/directus/directus",
            "Headless CMS and API platform that wraps any SQL database with a real-time GraphQL and REST API."),
        new("Appwrite", "Dev Tools", "appwrite/appwrite:latest", [("80", "80")], [], "unless-stopped", "https://hub.docker.com/r/appwrite/appwrite",
            "Open-source backend-as-a-service with auth, databases, storage, and serverless functions."),
        new("Supabase Studio", "Dev Tools", "supabase/studio:latest", [("3000", "3000")], [], "unless-stopped", "https://hub.docker.com/r/supabase/studio",
            "Web-based management interface for Supabase projects with table editor and SQL runner."),

        // ── Security & Auth ─────────────────────────────────────────
        new("Vaultwarden", "Security", "vaultwarden/server:latest", [("8080", "80")], [], "unless-stopped", "https://hub.docker.com/r/vaultwarden/server",
            "Lightweight Bitwarden-compatible password manager server written in Rust."),
        new("Authelia", "Security", "authelia/authelia:latest", [("9091", "9091")], [], "unless-stopped", "https://hub.docker.com/r/authelia/authelia",
            "Single sign-on and two-factor authentication portal for securing web applications."),
        new("Keycloak", "Security", "quay.io/keycloak/keycloak:latest", [("8080", "8080")],
            [("KEYCLOAK_ADMIN", "admin"), ("KEYCLOAK_ADMIN_PASSWORD", "changeme")], "unless-stopped", "https://hub.docker.com/r/keycloak/keycloak",
            "Enterprise identity and access management solution with SSO, OIDC, and SAML support."),
        new("Authentik", "Security", "ghcr.io/goauthentik/server:latest", [("9000", "9000"), ("9443", "9443")], [], "unless-stopped", "https://hub.docker.com/r/goauthentik/server",
            "Identity provider with support for OAuth2, SAML, LDAP, and SCIM for securing applications."),
        new("Vault", "Security", "hashicorp/vault:latest", [("8200", "8200")], [], "unless-stopped", "https://hub.docker.com/r/hashicorp/vault",
            "Secrets management tool for securely storing and accessing API keys, passwords, and certificates."),
        new("CrowdSec", "Security", "crowdsecurity/crowdsec:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/r/crowdsecurity/crowdsec",
            "Collaborative security engine that analyzes logs and shares threat intelligence across the community."),

        // ── Networking & VPN ────────────────────────────────────────
        new("Pi-hole", "Networking", "pihole/pihole:latest", [("53", "53"), ("8080", "80")],
            [("WEBPASSWORD", "changeme")], "unless-stopped", "https://hub.docker.com/r/pihole/pihole",
            "Network-wide ad blocker and DNS sinkhole that protects all devices on your network."),
        new("AdGuard Home", "Networking", "adguard/adguardhome:latest", [("53", "53"), ("3000", "3000"), ("80", "80")], [], "unless-stopped", "https://hub.docker.com/r/adguard/adguardhome",
            "Network-wide ad and tracker blocker with DNS-over-HTTPS, parental controls, and safe browsing."),
        new("WireGuard", "Networking", "lscr.io/linuxserver/wireguard:latest", [("51820", "51820")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/wireguard",
            "Modern, fast VPN tunnel using state-of-the-art cryptography with minimal attack surface."),
        new("Tailscale", "Networking", "tailscale/tailscale:latest", [], [], "unless-stopped", "https://hub.docker.com/r/tailscale/tailscale",
            "Zero-config mesh VPN built on WireGuard that creates a secure network between your devices."),
        new("WG-Easy", "Networking", "ghcr.io/wg-easy/wg-easy:latest", [("51820", "51820"), ("51821", "51821")],
            [("WG_HOST", "your-server-ip"), ("PASSWORD_HASH", "changeme")], "unless-stopped", "https://hub.docker.com/r/weejewel/wg-easy",
            "Simple web UI for managing WireGuard VPN with easy client configuration and QR codes."),
        new("OpenVPN", "Networking", "kylemanna/openvpn:latest", [("1194", "1194")], [], "unless-stopped", "https://hub.docker.com/r/kylemanna/openvpn",
            "Full-featured open-source VPN solution using SSL/TLS for secure point-to-point connections."),
        new("Cloudflare Tunnel", "Networking", "cloudflare/cloudflared:latest", [], [("TUNNEL_TOKEN", "your-token")], "unless-stopped", "https://hub.docker.com/r/cloudflare/cloudflared",
            "Secure tunnel to expose local services to the internet without opening ports on your firewall."),
        new("Speedtest Tracker", "Networking", "lscr.io/linuxserver/speedtest-tracker:latest", [("8080", "80")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/speedtest-tracker",
            "Automated internet speed test runner with historical tracking and performance graphs."),
        new("Technitium DNS", "Networking", "technitium/dns-server:latest", [("5380", "5380"), ("53", "53")], [], "unless-stopped", "https://hub.docker.com/r/technitium/dns-server",
            "Self-hosted DNS server with ad blocking, DNS-over-HTTPS, and advanced zone management."),

        // ── Productivity & Documents ────────────────────────────────
        new("Nextcloud", "Productivity", "nextcloud:latest", [("8080", "80")], [], "unless-stopped", "https://hub.docker.com/_/nextcloud",
            "Self-hosted cloud platform for file sync, sharing, collaboration, and office document editing."),
        new("Seafile", "Productivity", "seafileltd/seafile-mc:latest", [("80", "80")], [], "unless-stopped", "https://hub.docker.com/r/seafileltd/seafile-mc",
            "High-performance file sync and share solution with built-in encryption and team collaboration."),
        new("Paperless-ngx", "Productivity", "ghcr.io/paperless-ngx/paperless-ngx:latest", [("8000", "8000")], [], "unless-stopped", "https://hub.docker.com/r/paperlessngx/paperless-ngx",
            "Document management system that scans, indexes, and archives paper documents with OCR."),
        new("Bookstack", "Productivity", "lscr.io/linuxserver/bookstack:latest", [("6875", "80")],
            [("APP_URL", "http://localhost:6875"), ("DB_HOST", "bookstack-db"), ("DB_DATABASE", "bookstack"), ("DB_USERNAME", "bookstack"), ("DB_PASSWORD", "changeme")], "unless-stopped", "https://hub.docker.com/r/linuxserver/bookstack",
            "Simple, self-hosted wiki platform organized into books, chapters, and pages."),
        new("Wiki.js", "Productivity", "ghcr.io/requarks/wiki:2", [("3000", "3000")],
            [("DB_TYPE", "sqlite")], "unless-stopped", "https://hub.docker.com/r/requarks/wiki",
            "Modern wiki engine with Markdown support, visual editor, and Git-backed storage."),
        new("Outline", "Productivity", "outlinewiki/outline:latest", [("3000", "3000")], [], "unless-stopped", "https://hub.docker.com/r/outlinewiki/outline",
            "Beautiful team knowledge base and wiki with real-time collaboration and Slack integration."),
        new("Trilium", "Productivity", "zadam/trilium:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/r/zadam/trilium",
            "Hierarchical note-taking application with rich editing, scripting, and knowledge graph visualization."),
        new("Mealie", "Productivity", "hkotel/mealie:latest", [("9000", "9000")], [], "unless-stopped", "https://hub.docker.com/r/hkotel/mealie",
            "Self-hosted recipe manager with meal planning, shopping lists, and automatic URL import."),
        new("Stirling PDF", "Productivity", "frooodle/s-pdf:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/r/frooodle/s-pdf",
            "Self-hosted PDF manipulation tool for merging, splitting, converting, and editing PDF files."),
        new("Excalidraw", "Productivity", "excalidraw/excalidraw:latest", [("8080", "80")], [], "unless-stopped", "https://hub.docker.com/r/excalidraw/excalidraw",
            "Virtual collaborative whiteboard for sketching hand-drawn-style diagrams and wireframes."),
        new("Planka", "Productivity", "ghcr.io/plankanban/planka:latest", [("1337", "1337")], [], "unless-stopped", "https://hub.docker.com/r/meltyshev/planka",
            "Kanban board for project management with real-time updates, file attachments, and user roles."),
        new("Vikunja", "Productivity", "vikunja/vikunja:latest", [("3456", "3456")], [], "unless-stopped", "https://hub.docker.com/r/vikunja/vikunja",
            "Open-source to-do and task management app with lists, kanban boards, Gantt charts, and CalDAV."),

        // ── Communication ───────────────────────────────────────────
        new("Rocket.Chat", "Communication", "rocket.chat:latest", [("3000", "3000")], [], "unless-stopped", "https://hub.docker.com/_/rocket.chat",
            "Open-source team communication platform with channels, direct messaging, and video conferencing."),
        new("Mattermost", "Communication", "mattermost/mattermost-team-edition:latest", [("8065", "8065")], [], "unless-stopped", "https://hub.docker.com/r/mattermost/mattermost-team-edition",
            "Self-hosted Slack alternative for secure team messaging with integrations and playbooks."),
        new("Element (Matrix)", "Communication", "vectorim/element-web:latest", [("8080", "80")], [], "unless-stopped", "https://hub.docker.com/r/vectorim/element-web",
            "Web client for the Matrix decentralized communication protocol with end-to-end encryption."),
        new("Synapse (Matrix)", "Communication", "matrixdotorg/synapse:latest", [("8008", "8008")], [], "unless-stopped", "https://hub.docker.com/r/matrixdotorg/synapse",
            "Reference Matrix homeserver for decentralized, federated real-time communication."),
        new("Jitsi Meet", "Communication", "jitsi/web:latest", [("8443", "443"), ("80", "80")], [], "unless-stopped", "https://hub.docker.com/r/jitsi/web",
            "Self-hosted video conferencing platform with screen sharing, chat, and no account required."),

        // ── Utilities ───────────────────────────────────────────────
        new("Watchtower", "Utility", "containrrr/watchtower:latest", [], [], "unless-stopped", "https://hub.docker.com/r/containrrr/watchtower",
            "Automatically updates running Docker containers when new images are available."),
        new("FileBrowser", "Utility", "filebrowser/filebrowser:latest", [("8080", "80")], [], "unless-stopped", "https://hub.docker.com/r/filebrowser/filebrowser",
            "Web-based file manager for uploading, downloading, and managing files through a browser."),
        new("Duplicati", "Utility", "lscr.io/linuxserver/duplicati:latest", [("8200", "8200")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/duplicati",
            "Free backup client for creating encrypted, incremental backups to cloud and local storage."),
        new("Portainer Agent", "Utility", "portainer/agent:latest", [("9001", "9001")], [], "unless-stopped", "https://hub.docker.com/r/portainer/agent",
            "Lightweight agent for remote Docker host management through the Portainer interface."),
        new("Whoami", "Utility", "traefik/whoami:latest", [("8080", "80")], [], "unless-stopped", "https://hub.docker.com/r/traefik/whoami",
            "Tiny HTTP server that returns host info, useful for testing reverse proxy and load balancer setups."),
        new("IT Tools", "Utility", "corentinth/it-tools:latest", [("8080", "80")], [], "unless-stopped", "https://hub.docker.com/r/corentinth/it-tools",
            "Collection of handy developer utilities including encoders, converters, generators, and formatters."),
        new("CyberChef", "Utility", "ghcr.io/gchq/cyberchef:latest", [("8000", "80")], [], "unless-stopped", "https://hub.docker.com/r/mpepping/cyberchef",
            "Web-based data analysis tool for encoding, decoding, encrypting, and transforming data."),
        new("Syncthing", "Utility", "lscr.io/linuxserver/syncthing:latest", [("8384", "8384"), ("22000", "22000")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/syncthing",
            "Continuous peer-to-peer file synchronization tool that keeps folders in sync across devices."),
        new("Restic REST Server", "Utility", "restic/rest-server:latest", [("8000", "8000")], [], "unless-stopped", "https://hub.docker.com/r/restic/rest-server",
            "REST backend server for Restic backups, enabling fast and encrypted remote backup storage."),
        new("Diun", "Utility", "crazymax/diun:latest", [], [], "unless-stopped", "https://hub.docker.com/r/crazymax/diun",
            "Docker image update notifier that alerts you when new versions of your images are available."),
        new("Actual Budget", "Utility", "actualbudget/actual-server:latest", [("5006", "5006")], [], "unless-stopped", "https://hub.docker.com/r/actualbudget/actual-server",
            "Privacy-focused personal budgeting app with envelope budgeting and bank sync capabilities."),
        new("Ghostfolio", "Utility", "ghostfolio/ghostfolio:latest", [("3333", "3333")], [], "unless-stopped", "https://hub.docker.com/r/ghostfolio/ghostfolio",
            "Open-source wealth management dashboard for tracking stocks, ETFs, and crypto portfolios."),
        new("Linkwarden", "Utility", "ghcr.io/linkwarden/linkwarden:latest", [("3000", "3000")], [], "unless-stopped", "https://hub.docker.com/r/linkwarden/linkwarden",
            "Collaborative bookmark manager for saving, organizing, and archiving web pages."),
        new("Linkding", "Utility", "sissbruecker/linkding:latest", [("9090", "9090")], [], "unless-stopped", "https://hub.docker.com/r/sissbruecker/linkding",
            "Minimal self-hosted bookmark manager with tagging, search, and browser extension support."),
        new("Wallabag", "Utility", "wallabag/wallabag:latest", [("80", "80")], [], "unless-stopped", "https://hub.docker.com/r/wallabag/wallabag",
            "Self-hosted read-it-later app for saving and reading web articles offline."),
        new("FreshRSS", "Utility", "freshrss/freshrss:latest", [("8080", "80")], [], "unless-stopped", "https://hub.docker.com/r/freshrss/freshrss",
            "Self-hosted RSS feed aggregator with a responsive web UI and API for mobile apps."),
        new("Miniflux", "Utility", "miniflux/miniflux:latest", [("8080", "8080")],
            [("DATABASE_URL", "postgres://miniflux:changeme@db/miniflux?sslmode=disable"), ("RUN_MIGRATIONS", "1"), ("CREATE_ADMIN", "1"), ("ADMIN_USERNAME", "admin"), ("ADMIN_PASSWORD", "changeme")], "unless-stopped", "https://hub.docker.com/r/miniflux/miniflux",
            "Minimalist and opinionated RSS reader focused on simplicity, speed, and readability."),

        // ── Gaming ──────────────────────────────────────────────────
        new("Minecraft Server", "Gaming", "itzg/minecraft-server:latest", [("25565", "25565")],
            [("EULA", "TRUE")], "unless-stopped", "https://hub.docker.com/r/itzg/minecraft-server",
            "Dedicated Minecraft Java Edition server with automatic version management and mod support."),
        new("Valheim Server", "Gaming", "ghcr.io/lloesche/valheim-server:latest", [("2456", "2456"), ("2457", "2457")],
            [("SERVER_NAME", "MyServer"), ("WORLD_NAME", "MyWorld"), ("SERVER_PASS", "changeme")], "unless-stopped", "https://hub.docker.com/r/lloesche/valheim-server",
            "Dedicated Valheim game server with automatic updates, backups, and world management."),
        new("Satisfactory Server", "Gaming", "wolveix/satisfactory-server:latest", [("7777", "7777"), ("15000", "15000")], [], "unless-stopped", "https://hub.docker.com/r/wolveix/satisfactory-server",
            "Dedicated Satisfactory multiplayer server for building factories with friends."),
        new("Palworld Server", "Gaming", "thijsvanloef/palworld-server-docker:latest", [("8211", "8211")],
            [("PLAYERS", "16"), ("COMMUNITY", "false")], "unless-stopped", "https://hub.docker.com/r/thijsvanloef/palworld-server-docker",
            "Dedicated Palworld multiplayer server for catching Pals and surviving with friends."),

        // ── AI & Machine Learning ───────────────────────────────────
        new("Ollama", "AI", "ollama/ollama:latest", [("11434", "11434")], [], "unless-stopped", "https://hub.docker.com/r/ollama/ollama",
            "Run large language models locally with a simple API for Llama, Mistral, and other open models."),
        new("Open WebUI", "AI", "ghcr.io/open-webui/open-webui:main", [("3000", "8080")], [], "unless-stopped", "https://hub.docker.com/r/ghcr.io/open-webui/open-webui",
            "ChatGPT-style web interface for Ollama and OpenAI-compatible APIs with chat history and model management."),
        new("LocalAI", "AI", "localai/localai:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/r/localai/localai",
            "OpenAI-compatible local API for running LLMs, image generation, and audio models on consumer hardware."),
        new("Stable Diffusion WebUI", "AI", "ghcr.io/abetlen/llama-cpp-python:latest", [("8000", "8000")], [], "unless-stopped", "https://hub.docker.com/r/abetlen/llama-cpp-python",
            "Python bindings for llama.cpp providing a local OpenAI-compatible API for running LLMs."),
        new("Searxng", "AI", "searxng/searxng:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/r/searxng/searxng",
            "Privacy-respecting metasearch engine that aggregates results from multiple search providers."),
    ];
}

public record AppTemplate(
    string Name,
    string Category,
    string Image,
    List<(string Host, string Container)> Ports,
    List<(string Key, string Value)> Env,
    string RestartPolicy,
    string Url = "",
    string Description = ""
);
