namespace Kontainr.Models;

public static class AppTemplates
{
    public static readonly List<AppTemplate> Templates =
    [
        // ── Web Servers ─────────────────────────────────────────────
        new("Nginx", "Web Server", "nginx:alpine", [("80", "80")], [], "unless-stopped", "https://hub.docker.com/_/nginx"),
        new("Apache", "Web Server", "httpd:alpine", [("80", "80")], [], "unless-stopped", "https://hub.docker.com/_/httpd"),
        new("Caddy", "Web Server", "caddy:2-alpine", [("80", "80"), ("443", "443")], [], "unless-stopped", "https://hub.docker.com/_/caddy"),
        new("Lighttpd", "Web Server", "sebp/lighttpd:latest", [("80", "80")], [], "unless-stopped", "https://hub.docker.com/r/sebp/lighttpd"),
        new("OpenResty", "Web Server", "openresty/openresty:alpine", [("80", "80")], [], "unless-stopped", "https://hub.docker.com/r/openresty/openresty"),

        // ── Reverse Proxies & Load Balancers ────────────────────────
        new("Traefik", "Reverse Proxy", "traefik:v3.0", [("80", "80"), ("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/_/traefik"),
        new("Nginx Proxy Manager", "Reverse Proxy", "jc21/nginx-proxy-manager:latest", [("80", "80"), ("81", "81"), ("443", "443")], [], "unless-stopped", "https://hub.docker.com/r/jc21/nginx-proxy-manager"),
        new("HAProxy", "Load Balancer", "haproxy:alpine", [("80", "80"), ("8404", "8404")], [], "unless-stopped", "https://hub.docker.com/_/haproxy"),
        new("Envoy", "Reverse Proxy", "envoyproxy/envoy:v1.30-latest", [("10000", "10000"), ("9901", "9901")], [], "unless-stopped", "https://hub.docker.com/r/envoyproxy/envoy"),

        // ── Databases ───────────────────────────────────────────────
        new("PostgreSQL", "Database", "postgres:16-alpine", [("5432", "5432")],
            [("POSTGRES_PASSWORD", "changeme"), ("POSTGRES_DB", "mydb")], "unless-stopped", "https://hub.docker.com/_/postgres"),
        new("MySQL", "Database", "mysql:8", [("3306", "3306")],
            [("MYSQL_ROOT_PASSWORD", "changeme"), ("MYSQL_DATABASE", "mydb")], "unless-stopped", "https://hub.docker.com/_/mysql"),
        new("MariaDB", "Database", "mariadb:11", [("3306", "3306")],
            [("MARIADB_ROOT_PASSWORD", "changeme"), ("MARIADB_DATABASE", "mydb")], "unless-stopped", "https://hub.docker.com/_/mariadb"),
        new("MongoDB", "Database", "mongo:7", [("27017", "27017")], [], "unless-stopped", "https://hub.docker.com/_/mongo"),
        new("Redis", "Database", "redis:7-alpine", [("6379", "6379")], [], "unless-stopped", "https://hub.docker.com/_/redis"),
        new("Valkey", "Database", "valkey/valkey:latest", [("6379", "6379")], [], "unless-stopped", "https://hub.docker.com/r/valkey/valkey"),
        new("InfluxDB", "Database", "influxdb:2", [("8086", "8086")], [], "unless-stopped", "https://hub.docker.com/_/influxdb"),
        new("CouchDB", "Database", "couchdb:3", [("5984", "5984")],
            [("COUCHDB_USER", "admin"), ("COUCHDB_PASSWORD", "changeme")], "unless-stopped", "https://hub.docker.com/_/couchdb"),
        new("Cassandra", "Database", "cassandra:5", [("9042", "9042")], [], "unless-stopped", "https://hub.docker.com/_/cassandra"),
        new("Neo4j", "Database", "neo4j:5", [("7474", "7474"), ("7687", "7687")],
            [("NEO4J_AUTH", "neo4j/changeme")], "unless-stopped", "https://hub.docker.com/_/neo4j"),
        new("ClickHouse", "Database", "clickhouse/clickhouse-server:latest", [("8123", "8123"), ("9000", "9000")], [], "unless-stopped", "https://hub.docker.com/r/clickhouse/clickhouse-server"),
        new("SurrealDB", "Database", "surrealdb/surrealdb:latest", [("8000", "8000")], [], "unless-stopped", "https://hub.docker.com/r/surrealdb/surrealdb"),
        new("Elasticsearch", "Database", "docker.elastic.co/elasticsearch/elasticsearch:8.13.0", [("9200", "9200"), ("9300", "9300")],
            [("discovery.type", "single-node"), ("xpack.security.enabled", "false")], "unless-stopped", "https://hub.docker.com/_/elasticsearch"),
        new("Meilisearch", "Database", "getmeili/meilisearch:latest", [("7700", "7700")], [], "unless-stopped", "https://hub.docker.com/r/getmeili/meilisearch"),
        new("Typesense", "Database", "typesense/typesense:latest", [("8108", "8108")],
            [("TYPESENSE_API_KEY", "changeme"), ("TYPESENSE_DATA_DIR", "/data")], "unless-stopped", "https://hub.docker.com/r/typesense/typesense"),
        new("Minio", "Object Storage", "minio/minio:latest", [("9000", "9000"), ("9001", "9001")],
            [("MINIO_ROOT_USER", "minioadmin"), ("MINIO_ROOT_PASSWORD", "changeme")], "unless-stopped", "https://hub.docker.com/r/minio/minio"),
        new("Memcached", "Cache", "memcached:alpine", [("11211", "11211")], [], "unless-stopped", "https://hub.docker.com/_/memcached"),
        new("KeyDB", "Database", "eqalpha/keydb:latest", [("6379", "6379")], [], "unless-stopped", "https://hub.docker.com/r/eqalpha/keydb"),
        new("RethinkDB", "Database", "rethinkdb:latest", [("8080", "8080"), ("28015", "28015")], [], "unless-stopped", "https://hub.docker.com/_/rethinkdb"),
        new("ArangoDB", "Database", "arangodb:latest", [("8529", "8529")],
            [("ARANGO_ROOT_PASSWORD", "changeme")], "unless-stopped", "https://hub.docker.com/_/arangodb"),

        // ── DB Admin Tools ──────────────────────────────────────────
        new("Adminer", "DB Admin", "adminer:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/_/adminer"),
        new("pgAdmin", "DB Admin", "dpage/pgadmin4:latest", [("5050", "80")],
            [("PGADMIN_DEFAULT_EMAIL", "admin@local.dev"), ("PGADMIN_DEFAULT_PASSWORD", "changeme")], "unless-stopped", "https://hub.docker.com/r/dpage/pgadmin4"),
        new("phpMyAdmin", "DB Admin", "phpmyadmin:latest", [("8081", "80")],
            [("PMA_ARBITRARY", "1")], "unless-stopped", "https://hub.docker.com/_/phpmyadmin"),
        new("Mongo Express", "DB Admin", "mongo-express:latest", [("8081", "8081")],
            [("ME_CONFIG_BASICAUTH_USERNAME", "admin"), ("ME_CONFIG_BASICAUTH_PASSWORD", "changeme")], "unless-stopped", "https://hub.docker.com/_/mongo-express"),
        new("RedisInsight", "DB Admin", "redis/redisinsight:latest", [("5540", "5540")], [], "unless-stopped", "https://hub.docker.com/r/redis/redisinsight"),
        new("Kibana", "DB Admin", "docker.elastic.co/kibana/kibana:8.13.0", [("5601", "5601")], [], "unless-stopped", "https://hub.docker.com/_/kibana"),
        new("CloudBeaver", "DB Admin", "dbeaver/cloudbeaver:latest", [("8978", "8978")], [], "unless-stopped", "https://hub.docker.com/r/dbeaver/cloudbeaver"),

        // ── Message Queues ──────────────────────────────────────────
        new("RabbitMQ", "Message Queue", "rabbitmq:3-management-alpine", [("5672", "5672"), ("15672", "15672")], [], "unless-stopped", "https://hub.docker.com/_/rabbitmq"),
        new("NATS", "Message Queue", "nats:latest", [("4222", "4222"), ("8222", "8222")], [], "unless-stopped", "https://hub.docker.com/_/nats"),
        new("Mosquitto", "Message Queue", "eclipse-mosquitto:2", [("1883", "1883"), ("9001", "9001")], [], "unless-stopped", "https://hub.docker.com/_/eclipse-mosquitto"),
        new("Kafka (Redpanda)", "Message Queue", "redpandadata/redpanda:latest", [("9092", "9092"), ("8082", "8082")], [], "unless-stopped", "https://hub.docker.com/r/redpandadata/redpanda"),
        new("EMQX", "Message Queue", "emqx/emqx:latest", [("1883", "1883"), ("18083", "18083")], [], "unless-stopped", "https://hub.docker.com/r/emqx/emqx"),

        // ── Monitoring & Observability ───────────────────────────────
        new("Grafana", "Monitoring", "grafana/grafana:latest", [("3000", "3000")], [], "unless-stopped", "https://hub.docker.com/r/grafana/grafana"),
        new("Prometheus", "Monitoring", "prom/prometheus:latest", [("9090", "9090")], [], "unless-stopped", "https://hub.docker.com/r/prom/prometheus"),
        new("Uptime Kuma", "Monitoring", "louislam/uptime-kuma:latest", [("3001", "3001")], [], "unless-stopped", "https://hub.docker.com/r/louislam/uptime-kuma"),
        new("Netdata", "Monitoring", "netdata/netdata:latest", [("19999", "19999")], [], "unless-stopped", "https://hub.docker.com/r/netdata/netdata"),
        new("cAdvisor", "Monitoring", "gcr.io/cadvisor/cadvisor:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/r/google/cadvisor"),
        new("Loki", "Monitoring", "grafana/loki:latest", [("3100", "3100")], [], "unless-stopped", "https://hub.docker.com/r/grafana/loki"),
        new("Jaeger", "Monitoring", "jaegertracing/all-in-one:latest", [("16686", "16686"), ("4318", "4318")], [], "unless-stopped", "https://hub.docker.com/r/jaegertracing/all-in-one"),
        new("Zipkin", "Monitoring", "openzipkin/zipkin:latest", [("9411", "9411")], [], "unless-stopped", "https://hub.docker.com/r/openzipkin/zipkin"),
        new("Graylog", "Monitoring", "graylog/graylog:6.0", [("9000", "9000"), ("12201", "12201")],
            [("GRAYLOG_PASSWORD_SECRET", "changeme16chars!"), ("GRAYLOG_ROOT_PASSWORD_SHA2", "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918")], "unless-stopped", "https://hub.docker.com/r/graylog/graylog"),
        new("Zabbix", "Monitoring", "zabbix/zabbix-appliance:latest", [("8080", "80"), ("10051", "10051")], [], "unless-stopped", "https://hub.docker.com/r/zabbix/zabbix-appliance"),
        new("Healthchecks", "Monitoring", "lscr.io/linuxserver/healthchecks:latest", [("8000", "8000")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/healthchecks"),
        new("Gotify", "Monitoring", "gotify/server:latest", [("8080", "80")], [], "unless-stopped", "https://hub.docker.com/r/gotify/server"),
        new("Ntfy", "Monitoring", "binwiederhier/ntfy:latest", [("8080", "80")], [], "unless-stopped", "https://hub.docker.com/r/binwiederhier/ntfy"),
        new("Changedetection.io", "Monitoring", "ghcr.io/dgtlmoon/changedetection.io:latest", [("5000", "5000")], [], "unless-stopped", "https://hub.docker.com/r/dgtlmoon/changedetection.io"),
        new("Dozzle", "Monitoring", "amir20/dozzle:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/r/amir20/dozzle"),

        // ── Home Automation ─────────────────────────────────────────
        new("Home Assistant", "Home Automation", "homeassistant/home-assistant:stable", [("8123", "8123")], [], "unless-stopped", "https://hub.docker.com/r/homeassistant/home-assistant"),
        new("Node-RED", "Home Automation", "nodered/node-red:latest", [("1880", "1880")], [], "unless-stopped", "https://hub.docker.com/r/nodered/node-red"),
        new("Mosquitto", "Home Automation", "eclipse-mosquitto:2", [("1883", "1883")], [], "unless-stopped", "https://hub.docker.com/_/eclipse-mosquitto"),
        new("Zigbee2MQTT", "Home Automation", "koenkk/zigbee2mqtt:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/r/koenkk/zigbee2mqtt"),
        new("ESPHome", "Home Automation", "ghcr.io/esphome/esphome:latest", [("6052", "6052")], [], "unless-stopped", "https://hub.docker.com/r/esphome/esphome"),
        new("Scrypted", "Home Automation", "koush/scrypted:latest", [("10443", "10443")], [], "unless-stopped", "https://hub.docker.com/r/koush/scrypted"),

        // ── Dashboards ──────────────────────────────────────────────
        new("Heimdall", "Dashboard", "lscr.io/linuxserver/heimdall:latest", [("80", "80"), ("443", "443")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/heimdall"),
        new("Homepage", "Dashboard", "ghcr.io/gethomepage/homepage:latest", [("3000", "3000")], [], "unless-stopped", "https://hub.docker.com/r/gethomepage/homepage"),
        new("Homarr", "Dashboard", "ghcr.io/ajnart/homarr:latest", [("7575", "7575")], [], "unless-stopped", "https://hub.docker.com/r/ajnart/homarr"),
        new("Dashy", "Dashboard", "lissy93/dashy:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/r/lissy93/dashy"),
        new("Organizr", "Dashboard", "organizr/organizr:latest", [("80", "80")], [], "unless-stopped", "https://hub.docker.com/r/organizr/organizr"),
        new("Flame", "Dashboard", "pawelmalak/flame:latest", [("5005", "5005")], [], "unless-stopped", "https://hub.docker.com/r/pawelmalak/flame"),

        // ── Media Servers ───────────────────────────────────────────
        new("Jellyfin", "Media", "jellyfin/jellyfin:latest", [("8096", "8096")], [], "unless-stopped", "https://hub.docker.com/r/jellyfin/jellyfin"),
        new("Plex", "Media", "lscr.io/linuxserver/plex:latest", [("32400", "32400")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/plex"),
        new("Emby", "Media", "emby/embyserver:latest", [("8096", "8096")], [], "unless-stopped", "https://hub.docker.com/r/emby/embyserver"),
        new("Navidrome", "Media", "deluan/navidrome:latest", [("4533", "4533")], [], "unless-stopped", "https://hub.docker.com/r/deluan/navidrome"),
        new("Airsonic-Advanced", "Media", "lscr.io/linuxserver/airsonic-advanced:latest", [("4040", "4040")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/airsonic-advanced"),
        new("Calibre-Web", "Media", "lscr.io/linuxserver/calibre-web:latest", [("8083", "8083")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/calibre-web"),
        new("Kavita", "Media", "jvmilazz0/kavita:latest", [("5000", "5000")], [], "unless-stopped", "https://hub.docker.com/r/jvmilazz0/kavita"),
        new("Audiobookshelf", "Media", "ghcr.io/advplyr/audiobookshelf:latest", [("13378", "80")], [], "unless-stopped", "https://hub.docker.com/r/advplyr/audiobookshelf"),
        new("PhotoPrism", "Media", "photoprism/photoprism:latest", [("2342", "2342")],
            [("PHOTOPRISM_ADMIN_PASSWORD", "changeme")], "unless-stopped", "https://hub.docker.com/r/photoprism/photoprism"),
        new("Immich", "Media", "ghcr.io/immich-app/immich-server:latest", [("2283", "2283")], [], "unless-stopped", "https://hub.docker.com/r/altran1502/immich-server"),
        new("Stash", "Media", "stashapp/stash:latest", [("9999", "9999")], [], "unless-stopped", "https://hub.docker.com/r/stashapp/stash"),

        // ── *arr Stack ──────────────────────────────────────────────
        new("Sonarr", "*arr Stack", "lscr.io/linuxserver/sonarr:latest", [("8989", "8989")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/sonarr"),
        new("Radarr", "*arr Stack", "lscr.io/linuxserver/radarr:latest", [("7878", "7878")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/radarr"),
        new("Lidarr", "*arr Stack", "lscr.io/linuxserver/lidarr:latest", [("8686", "8686")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/lidarr"),
        new("Readarr", "*arr Stack", "lscr.io/linuxserver/readarr:develop", [("8787", "8787")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/readarr"),
        new("Whisparr", "*arr Stack", "ghcr.io/hotio/whisparr:latest", [("6969", "6969")], [], "unless-stopped", "https://hub.docker.com/r/hotio/whisparr"),
        new("Prowlarr", "*arr Stack", "lscr.io/linuxserver/prowlarr:latest", [("9696", "9696")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/prowlarr"),
        new("Bazarr", "*arr Stack", "lscr.io/linuxserver/bazarr:latest", [("6767", "6767")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/bazarr"),
        new("Overseerr", "*arr Stack", "lscr.io/linuxserver/overseerr:latest", [("5055", "5055")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/overseerr"),
        new("Requestrr", "*arr Stack", "thomst08/requestrr:latest", [("4545", "4545")], [], "unless-stopped", "https://hub.docker.com/r/thomst08/requestrr"),
        new("Tautulli", "*arr Stack", "lscr.io/linuxserver/tautulli:latest", [("8181", "8181")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/tautulli"),
        new("Flaresolverr", "*arr Stack", "ghcr.io/flaresolverr/flaresolverr:latest", [("8191", "8191")], [], "unless-stopped", "https://hub.docker.com/r/flaresolverr/flaresolverr"),
        new("Recyclarr", "*arr Stack", "ghcr.io/recyclarr/recyclarr:latest", [], [], "unless-stopped", "https://hub.docker.com/r/recyclarr/recyclarr"),
        new("Autobrr", "*arr Stack", "ghcr.io/autobrr/autobrr:latest", [("7474", "7474")], [], "unless-stopped", "https://hub.docker.com/r/autobrr/autobrr"),
        new("Unpackerr", "*arr Stack", "ghcr.io/unpackerr/unpackerr:latest", [], [], "unless-stopped", "https://hub.docker.com/r/unpackerr/unpackerr"),
        new("Jackett", "*arr Stack", "lscr.io/linuxserver/jackett:latest", [("9117", "9117")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/jackett"),

        // ── Download Clients ────────────────────────────────────────
        new("qBittorrent", "Download Client", "lscr.io/linuxserver/qbittorrent:latest", [("8080", "8080"), ("6881", "6881")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/qbittorrent"),
        new("Transmission", "Download Client", "lscr.io/linuxserver/transmission:latest", [("9091", "9091"), ("51413", "51413")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/transmission"),
        new("Deluge", "Download Client", "lscr.io/linuxserver/deluge:latest", [("8112", "8112"), ("6881", "6881")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/deluge"),
        new("SABnzbd", "Download Client", "lscr.io/linuxserver/sabnzbd:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/sabnzbd"),
        new("NZBGet", "Download Client", "lscr.io/linuxserver/nzbget:latest", [("6789", "6789")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/nzbget"),
        new("JDownloader 2", "Download Client", "jlesage/jdownloader-2:latest", [("5800", "5800")], [], "unless-stopped", "https://hub.docker.com/r/jlesage/jdownloader-2"),
        new("Aria2", "Download Client", "p3terx/aria2-pro:latest", [("6800", "6800"), ("6888", "6888")], [], "unless-stopped", "https://hub.docker.com/r/p3terx/aria2-pro"),

        // ── Dev Tools ───────────────────────────────────────────────
        new("Gitea", "Dev Tools", "gitea/gitea:latest", [("3000", "3000"), ("2222", "22")], [], "unless-stopped", "https://hub.docker.com/r/gitea/gitea"),
        new("GitLab", "Dev Tools", "gitlab/gitlab-ce:latest", [("8929", "80"), ("2224", "22")], [], "unless-stopped", "https://hub.docker.com/r/gitlab/gitlab-ce"),
        new("Forgejo", "Dev Tools", "codeberg.org/forgejo/forgejo:latest", [("3000", "3000"), ("2222", "22")], [], "unless-stopped", "https://hub.docker.com/r/codeberg/forgejo"),
        new("Code Server", "Dev Tools", "lscr.io/linuxserver/code-server:latest", [("8443", "8443")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/code-server"),
        new("Drone", "Dev Tools", "drone/drone:latest", [("8000", "80")], [], "unless-stopped", "https://hub.docker.com/r/drone/drone"),
        new("Jenkins", "Dev Tools", "jenkins/jenkins:lts", [("8080", "8080"), ("50000", "50000")], [], "unless-stopped", "https://hub.docker.com/r/jenkins/jenkins"),
        new("SonarQube", "Dev Tools", "sonarqube:community", [("9000", "9000")], [], "unless-stopped", "https://hub.docker.com/_/sonarqube"),
        new("Registry", "Dev Tools", "registry:2", [("5000", "5000")], [], "unless-stopped", "https://hub.docker.com/_/registry"),
        new("Nexus", "Dev Tools", "sonatype/nexus3:latest", [("8081", "8081")], [], "unless-stopped", "https://hub.docker.com/r/sonatype/nexus3"),
        new("Verdaccio", "Dev Tools", "verdaccio/verdaccio:latest", [("4873", "4873")], [], "unless-stopped", "https://hub.docker.com/r/verdaccio/verdaccio"),
        new("n8n", "Dev Tools", "n8nio/n8n:latest", [("5678", "5678")], [], "unless-stopped", "https://hub.docker.com/r/n8nio/n8n"),
        new("Budibase", "Dev Tools", "budibase/budibase:latest", [("10000", "80")], [], "unless-stopped", "https://hub.docker.com/r/budibase/budibase"),
        new("Nocodb", "Dev Tools", "nocodb/nocodb:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/r/nocodb/nocodb"),
        new("Directus", "Dev Tools", "directus/directus:latest", [("8055", "8055")],
            [("SECRET", "changeme"), ("ADMIN_EMAIL", "admin@local.dev"), ("ADMIN_PASSWORD", "changeme")], "unless-stopped", "https://hub.docker.com/r/directus/directus"),
        new("Appwrite", "Dev Tools", "appwrite/appwrite:latest", [("80", "80")], [], "unless-stopped", "https://hub.docker.com/r/appwrite/appwrite"),
        new("Supabase Studio", "Dev Tools", "supabase/studio:latest", [("3000", "3000")], [], "unless-stopped", "https://hub.docker.com/r/supabase/studio"),

        // ── Security & Auth ─────────────────────────────────────────
        new("Vaultwarden", "Security", "vaultwarden/server:latest", [("8080", "80")], [], "unless-stopped", "https://hub.docker.com/r/vaultwarden/server"),
        new("Authelia", "Security", "authelia/authelia:latest", [("9091", "9091")], [], "unless-stopped", "https://hub.docker.com/r/authelia/authelia"),
        new("Keycloak", "Security", "quay.io/keycloak/keycloak:latest", [("8080", "8080")],
            [("KEYCLOAK_ADMIN", "admin"), ("KEYCLOAK_ADMIN_PASSWORD", "changeme")], "unless-stopped", "https://hub.docker.com/r/keycloak/keycloak"),
        new("Authentik", "Security", "ghcr.io/goauthentik/server:latest", [("9000", "9000"), ("9443", "9443")], [], "unless-stopped", "https://hub.docker.com/r/goauthentik/server"),
        new("Vault", "Security", "hashicorp/vault:latest", [("8200", "8200")], [], "unless-stopped", "https://hub.docker.com/r/hashicorp/vault"),
        new("CrowdSec", "Security", "crowdsecurity/crowdsec:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/r/crowdsecurity/crowdsec"),

        // ── Networking & VPN ────────────────────────────────────────
        new("Pi-hole", "Networking", "pihole/pihole:latest", [("53", "53"), ("8080", "80")],
            [("WEBPASSWORD", "changeme")], "unless-stopped", "https://hub.docker.com/r/pihole/pihole"),
        new("AdGuard Home", "Networking", "adguard/adguardhome:latest", [("53", "53"), ("3000", "3000"), ("80", "80")], [], "unless-stopped", "https://hub.docker.com/r/adguard/adguardhome"),
        new("WireGuard", "Networking", "lscr.io/linuxserver/wireguard:latest", [("51820", "51820")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/wireguard"),
        new("Tailscale", "Networking", "tailscale/tailscale:latest", [], [], "unless-stopped", "https://hub.docker.com/r/tailscale/tailscale"),
        new("WG-Easy", "Networking", "ghcr.io/wg-easy/wg-easy:latest", [("51820", "51820"), ("51821", "51821")],
            [("WG_HOST", "your-server-ip"), ("PASSWORD_HASH", "changeme")], "unless-stopped", "https://hub.docker.com/r/weejewel/wg-easy"),
        new("OpenVPN", "Networking", "kylemanna/openvpn:latest", [("1194", "1194")], [], "unless-stopped", "https://hub.docker.com/r/kylemanna/openvpn"),
        new("Cloudflare Tunnel", "Networking", "cloudflare/cloudflared:latest", [], [("TUNNEL_TOKEN", "your-token")], "unless-stopped", "https://hub.docker.com/r/cloudflare/cloudflared"),
        new("Speedtest Tracker", "Networking", "lscr.io/linuxserver/speedtest-tracker:latest", [("8080", "80")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/speedtest-tracker"),
        new("Technitium DNS", "Networking", "technitium/dns-server:latest", [("5380", "5380"), ("53", "53")], [], "unless-stopped", "https://hub.docker.com/r/technitium/dns-server"),

        // ── Productivity & Documents ────────────────────────────────
        new("Nextcloud", "Productivity", "nextcloud:latest", [("8080", "80")], [], "unless-stopped", "https://hub.docker.com/_/nextcloud"),
        new("Seafile", "Productivity", "seafileltd/seafile-mc:latest", [("80", "80")], [], "unless-stopped", "https://hub.docker.com/r/seafileltd/seafile-mc"),
        new("Paperless-ngx", "Productivity", "ghcr.io/paperless-ngx/paperless-ngx:latest", [("8000", "8000")], [], "unless-stopped", "https://hub.docker.com/r/paperlessngx/paperless-ngx"),
        new("Bookstack", "Productivity", "lscr.io/linuxserver/bookstack:latest", [("6875", "80")],
            [("APP_URL", "http://localhost:6875"), ("DB_HOST", "bookstack-db"), ("DB_DATABASE", "bookstack"), ("DB_USERNAME", "bookstack"), ("DB_PASSWORD", "changeme")], "unless-stopped", "https://hub.docker.com/r/linuxserver/bookstack"),
        new("Wiki.js", "Productivity", "ghcr.io/requarks/wiki:2", [("3000", "3000")],
            [("DB_TYPE", "sqlite")], "unless-stopped", "https://hub.docker.com/r/requarks/wiki"),
        new("Outline", "Productivity", "outlinewiki/outline:latest", [("3000", "3000")], [], "unless-stopped", "https://hub.docker.com/r/outlinewiki/outline"),
        new("Trilium", "Productivity", "zadam/trilium:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/r/zadam/trilium"),
        new("Mealie", "Productivity", "hkotel/mealie:latest", [("9000", "9000")], [], "unless-stopped", "https://hub.docker.com/r/hkotel/mealie"),
        new("Stirling PDF", "Productivity", "frooodle/s-pdf:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/r/frooodle/s-pdf"),
        new("Excalidraw", "Productivity", "excalidraw/excalidraw:latest", [("8080", "80")], [], "unless-stopped", "https://hub.docker.com/r/excalidraw/excalidraw"),
        new("Planka", "Productivity", "ghcr.io/plankanban/planka:latest", [("1337", "1337")], [], "unless-stopped", "https://hub.docker.com/r/meltyshev/planka"),
        new("Vikunja", "Productivity", "vikunja/vikunja:latest", [("3456", "3456")], [], "unless-stopped", "https://hub.docker.com/r/vikunja/vikunja"),

        // ── Communication ───────────────────────────────────────────
        new("Rocket.Chat", "Communication", "rocket.chat:latest", [("3000", "3000")], [], "unless-stopped", "https://hub.docker.com/_/rocket.chat"),
        new("Mattermost", "Communication", "mattermost/mattermost-team-edition:latest", [("8065", "8065")], [], "unless-stopped", "https://hub.docker.com/r/mattermost/mattermost-team-edition"),
        new("Element (Matrix)", "Communication", "vectorim/element-web:latest", [("8080", "80")], [], "unless-stopped", "https://hub.docker.com/r/vectorim/element-web"),
        new("Synapse (Matrix)", "Communication", "matrixdotorg/synapse:latest", [("8008", "8008")], [], "unless-stopped", "https://hub.docker.com/r/matrixdotorg/synapse"),
        new("Jitsi Meet", "Communication", "jitsi/web:latest", [("8443", "443"), ("80", "80")], [], "unless-stopped", "https://hub.docker.com/r/jitsi/web"),

        // ── Utilities ───────────────────────────────────────────────
        new("Watchtower", "Utility", "containrrr/watchtower:latest", [], [], "unless-stopped", "https://hub.docker.com/r/containrrr/watchtower"),
        new("FileBrowser", "Utility", "filebrowser/filebrowser:latest", [("8080", "80")], [], "unless-stopped", "https://hub.docker.com/r/filebrowser/filebrowser"),
        new("Duplicati", "Utility", "lscr.io/linuxserver/duplicati:latest", [("8200", "8200")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/duplicati"),
        new("Portainer Agent", "Utility", "portainer/agent:latest", [("9001", "9001")], [], "unless-stopped", "https://hub.docker.com/r/portainer/agent"),
        new("Whoami", "Utility", "traefik/whoami:latest", [("8080", "80")], [], "unless-stopped", "https://hub.docker.com/r/traefik/whoami"),
        new("IT Tools", "Utility", "corentinth/it-tools:latest", [("8080", "80")], [], "unless-stopped", "https://hub.docker.com/r/corentinth/it-tools"),
        new("CyberChef", "Utility", "ghcr.io/gchq/cyberchef:latest", [("8000", "80")], [], "unless-stopped", "https://hub.docker.com/r/mpepping/cyberchef"),
        new("Syncthing", "Utility", "lscr.io/linuxserver/syncthing:latest", [("8384", "8384"), ("22000", "22000")], [], "unless-stopped", "https://hub.docker.com/r/linuxserver/syncthing"),
        new("Restic REST Server", "Utility", "restic/rest-server:latest", [("8000", "8000")], [], "unless-stopped", "https://hub.docker.com/r/restic/rest-server"),
        new("Diun", "Utility", "crazymax/diun:latest", [], [], "unless-stopped", "https://hub.docker.com/r/crazymax/diun"),
        new("Actual Budget", "Utility", "actualbudget/actual-server:latest", [("5006", "5006")], [], "unless-stopped", "https://hub.docker.com/r/actualbudget/actual-server"),
        new("Ghostfolio", "Utility", "ghostfolio/ghostfolio:latest", [("3333", "3333")], [], "unless-stopped", "https://hub.docker.com/r/ghostfolio/ghostfolio"),
        new("Linkwarden", "Utility", "ghcr.io/linkwarden/linkwarden:latest", [("3000", "3000")], [], "unless-stopped", "https://hub.docker.com/r/linkwarden/linkwarden"),
        new("Linkding", "Utility", "sissbruecker/linkding:latest", [("9090", "9090")], [], "unless-stopped", "https://hub.docker.com/r/sissbruecker/linkding"),
        new("Wallabag", "Utility", "wallabag/wallabag:latest", [("80", "80")], [], "unless-stopped", "https://hub.docker.com/r/wallabag/wallabag"),
        new("FreshRSS", "Utility", "freshrss/freshrss:latest", [("8080", "80")], [], "unless-stopped", "https://hub.docker.com/r/freshrss/freshrss"),
        new("Miniflux", "Utility", "miniflux/miniflux:latest", [("8080", "8080")],
            [("DATABASE_URL", "postgres://miniflux:changeme@db/miniflux?sslmode=disable"), ("RUN_MIGRATIONS", "1"), ("CREATE_ADMIN", "1"), ("ADMIN_USERNAME", "admin"), ("ADMIN_PASSWORD", "changeme")], "unless-stopped", "https://hub.docker.com/r/miniflux/miniflux"),

        // ── Gaming ──────────────────────────────────────────────────
        new("Minecraft Server", "Gaming", "itzg/minecraft-server:latest", [("25565", "25565")],
            [("EULA", "TRUE")], "unless-stopped", "https://hub.docker.com/r/itzg/minecraft-server"),
        new("Valheim Server", "Gaming", "ghcr.io/lloesche/valheim-server:latest", [("2456", "2456"), ("2457", "2457")],
            [("SERVER_NAME", "MyServer"), ("WORLD_NAME", "MyWorld"), ("SERVER_PASS", "changeme")], "unless-stopped", "https://hub.docker.com/r/lloesche/valheim-server"),
        new("Satisfactory Server", "Gaming", "wolveix/satisfactory-server:latest", [("7777", "7777"), ("15000", "15000")], [], "unless-stopped", "https://hub.docker.com/r/wolveix/satisfactory-server"),
        new("Palworld Server", "Gaming", "thijsvanloef/palworld-server-docker:latest", [("8211", "8211")],
            [("PLAYERS", "16"), ("COMMUNITY", "false")], "unless-stopped", "https://hub.docker.com/r/thijsvanloef/palworld-server-docker"),

        // ── AI & Machine Learning ───────────────────────────────────
        new("Ollama", "AI", "ollama/ollama:latest", [("11434", "11434")], [], "unless-stopped", "https://hub.docker.com/r/ollama/ollama"),
        new("Open WebUI", "AI", "ghcr.io/open-webui/open-webui:main", [("3000", "8080")], [], "unless-stopped", "https://hub.docker.com/r/ghcr.io/open-webui/open-webui"),
        new("LocalAI", "AI", "localai/localai:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/r/localai/localai"),
        new("Stable Diffusion WebUI", "AI", "ghcr.io/abetlen/llama-cpp-python:latest", [("8000", "8000")], [], "unless-stopped", "https://hub.docker.com/r/abetlen/llama-cpp-python"),
        new("Searxng", "AI", "searxng/searxng:latest", [("8080", "8080")], [], "unless-stopped", "https://hub.docker.com/r/searxng/searxng"),
    ];
}

public record AppTemplate(
    string Name,
    string Category,
    string Image,
    List<(string Host, string Container)> Ports,
    List<(string Key, string Value)> Env,
    string RestartPolicy,
    string Url = ""
);
